import type { SelfImproveTestSpec } from "./testSpec.js";

function serialize(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function escapeComment(value: string): string {
  return value.replace(/\*\//g, "* /");
}

export function emitSelfImproveTestSource(spec: SelfImproveTestSpec): string {
  const rationale = spec.rationale
    ? `\n${escapeComment(spec.rationale)}\n`
    : "\n";

  return `/*
Generated by the mcp-command-compiler self-improve workflow.${rationale}*/

import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import ts from "typescript";
import { describe, expect, it } from "vitest";
import { compileMcpCommands } from "../src/core/compile.js";
import type { McpToolDefinition } from "../src/types/mcpTool.js";

async function loadParseCommandFromTools(
  tools: McpToolDefinition[],
  options?: Parameters<typeof compileMcpCommands>[1]
) {
  const output = compileMcpCommands(tools, options);
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "mcp-command-compiler-self-improve-"));
  const modulePath = path.join(tempDir, "generatedParser.mjs");
  const transpiled = ts.transpileModule(output.parserSource, {
    compilerOptions: {
      module: ts.ModuleKind.ES2022,
      target: ts.ScriptTarget.ES2022
    }
  });

  await writeFile(modulePath, transpiled.outputText, "utf8");
  const parserModule = await import(pathToFileURL(modulePath).href);
  return parserModule.parseCommand as (input: string) => {
    matched: boolean;
    toolName?: string;
    args?: Record<string, unknown>;
    reason?: string;
    fallback?: "llm";
    source?: "exact" | "prefix" | "regex" | "builtin";
    requiresConfirmation?: boolean;
  };
}

const tools: McpToolDefinition[] = ${serialize(spec.tools)};
const compileOptions = ${spec.options ? serialize(spec.options) : "undefined"};
const matchCases = ${serialize(spec.matches)};
const fallbackCases = ${serialize(spec.fallbacks)};

describe(${JSON.stringify(spec.title)}, () => {
  it("matches clear commands and falls back conservatively", async () => {
    const parseCommand = await loadParseCommandFromTools(tools, compileOptions);

    for (const matchCase of matchCases) {
      const expected: Record<string, unknown> = {
        matched: true
      };

      if (matchCase.toolName) expected.toolName = matchCase.toolName;
      if (matchCase.args) expected.args = matchCase.args;
      if (matchCase.source) expected.source = matchCase.source;
      if (typeof matchCase.requiresConfirmation === "boolean") {
        expected.requiresConfirmation = matchCase.requiresConfirmation;
      }

      expect(parseCommand(matchCase.input)).toMatchObject(expected);
    }

    for (const fallbackCase of fallbackCases) {
      const result = parseCommand(fallbackCase.input);
      expect(result).toMatchObject({
        matched: false,
        fallback: "llm"
      });

      if (!result.matched && fallbackCase.reasonIncludes) {
        expect(result.reason).toContain(fallbackCase.reasonIncludes);
      }
    }
  });
});
`;
}
